"""Write tracker results as JSON, CSV, Markdown, or a self-contained HTML report."""

from __future__ import annotations

import csv
import io
import json
from datetime import date
from html import escape

from .analysis import TrackerResult

DISCLAIMER = (
    "This report is generated by an automated monitoring aid from the data supplied. Projections assume "
    "the recent enrollment pace continues and are estimates, not commitments. It does not replace a formal "
    "assessment or the judgment of a qualified auditor."
)
COLORS = {"coverage": "#0F766E", "pr": "#B45309", "admin": "#475569", "target": "#9AA5B1"}


def _pct(v) -> str:
    return "n/a" if v is None else f"{v:.0f}%"


def _month(iso: str) -> str:
    return date.fromisoformat(iso).strftime("%b %Y")


def grouped_findings(result: TrackerResult) -> list[dict]:
    groups: dict[str, dict] = {}
    for f in result.findings:
        g = groups.setdefault(f.rule_id, {"finding": f, "accounts": [], "details": []})
        if f.account:
            g["accounts"].append(f.account)
            g["details"].append(f"{f.account}: {f.detail}")
        else:
            g["details"].append(f.detail)
    return list(groups.values())


def trend_svg(result: TrackerResult, target: float = 100.0) -> str:
    """A small, dependency-free line chart of coverage over time."""
    snaps = result.snapshots
    w, h, left, right, top, bottom = 640, 260, 44, 16, 16, 36
    pw, ph = w - left - right, h - top - bottom
    n = len(snaps)

    def x(i: int) -> float:
        return left + (pw * i / (n - 1) if n > 1 else pw / 2)

    def y(v: float) -> float:
        return top + ph * (1 - v / 100)

    parts = [f'<svg viewBox="0 0 {w} {h}" role="img" aria-label="MFA coverage trend" '
             f'style="width:100%;height:auto;font:12px sans-serif">']
    for v in (0, 25, 50, 75, 100):
        parts.append(f'<line x1="{left}" x2="{w - right}" y1="{y(v)}" y2="{y(v)}" stroke="#E2E8F0"/>'
                     f'<text x="{left - 8}" y="{y(v) + 4}" text-anchor="end" fill="#52606D">{v}%</text>')
    parts.append(f'<line x1="{left}" x2="{w - right}" y1="{y(target)}" y2="{y(target)}" '
                 f'stroke="{COLORS["target"]}" stroke-dasharray="2 4" stroke-width="2"/>')
    for i, s in enumerate(snaps):
        parts.append(f'<text x="{x(i)}" y="{h - 12}" text-anchor="middle" fill="#52606D">'
                     f'{escape(date.fromisoformat(s.snapshot).strftime("%b"))}</text>')
    series = [("coverage", [s.mfa_pct for s in snaps], ""),
              ("pr", [s.phishing_resistant_pct for s in snaps], ""),
              ("admin", [s.admin_phishing_resistant_pct for s in snaps], ' stroke-dasharray="6 4"')]
    for key, vals, dash in series:
        pts = [(x(i), y(v)) for i, v in enumerate(vals) if v is not None]
        if not pts:
            continue
        path = " ".join(f"{px:.1f},{py:.1f}" for px, py in pts)
        parts.append(f'<polyline points="{path}" fill="none" stroke="{COLORS[key]}" stroke-width="3"{dash}/>')
        parts += [f'<circle cx="{px:.1f}" cy="{py:.1f}" r="3.5" fill="{COLORS[key]}"/>' for px, py in pts]
    parts.append("</svg>")
    return "".join(parts)


def to_json(result: TrackerResult) -> str:
    return json.dumps(result.to_dict(), indent=2, default=str)


def to_csv(result: TrackerResult) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["account", "rule_id", "title", "severity", "controls", "detail", "remediation"])
    for f in result.findings:
        w.writerow([f.account or "(organization)", f.rule_id, f.title, f.severity, "; ".join(f.controls),
                    f.detail, f.remediation])
    return buf.getvalue()


def to_markdown(result: TrackerResult) -> str:
    L, F = result.latest, result.first
    lines = [
        f"# MFA rollout report: {result.organization}",
        "",
        f"{len(result.snapshots)} snapshots, {_month(F.snapshot)} to {_month(L.snapshot)} | Generated {result.generated_at}",
        "",
        f"- MFA coverage: **{_pct(L.mfa_pct)}** (from {_pct(F.mfa_pct)})",
        f"- Phishing-resistant MFA, all accounts: **{_pct(L.phishing_resistant_pct)}**",
        f"- Administrators with phishing-resistant MFA: **{_pct(L.admin_phishing_resistant_pct)}**",
    ]
    if result.signins["provided"]:
        lines.append(f"- Successful sign-ins without MFA: **{_pct(result.signins['without_mfa_pct'])}** "
                     f"({result.signins['without_mfa']} of {result.signins['successful_sign_ins']})")
    lines += ["", "## Progress toward targets", "", "| Measure | Now | Target | Status | Outlook |", "|---|---|---|---|---|"]
    for p in result.projections:
        lines.append(f"| {p.measure} | {p.current_pct:.0f}% | {p.target_pct:.0f}% by {p.target_date} | {p.status} | {p.explanation} |")
    lines += ["", "## Coverage over time", "", "| Snapshot | Accounts | MFA | Phishing-resistant | Admins phishing-resistant |",
              "|---|---|---|---|---|"]
    for s in result.snapshots:
        lines.append(f"| {s.snapshot} | {s.accounts} | {_pct(s.mfa_pct)} | {_pct(s.phishing_resistant_pct)} | "
                     f"{_pct(s.admin_phishing_resistant_pct)} |")
    lines += ["", "## Departments (latest snapshot)", "", "| Department | Accounts | MFA | Change since first | Without MFA |",
              "|---|---|---|---|---|"]
    for d in result.departments:
        ch = "n/a" if d["change_pts"] is None else f"{d['change_pts']:+.0f} pts"
        lines.append(f"| {d['department']} | {d['accounts']} | {_pct(d['mfa_pct'])} | {ch} | {d['without_mfa']} |")
    lines += ["", "## Findings by priority", ""]
    groups = grouped_findings(result)
    if not groups:
        lines.append("No findings.")
    for g in groups:
        f = g["finding"]
        lines += [f"### [{f.severity.upper()}] {f.rule_id}: {f.title}", f"Controls: {', '.join(f.controls)}  "]
        lines += [f"- {d}" for d in g["details"]]
        lines += ["", f"Remediation: {f.remediation}", ""]
    lines += [f"_{DISCLAIMER}_", ""]
    return "\n".join(lines)


_CSS = """
:root{--ink:#1f2933;--muted:#52606d;--line:#d9e2ec;--paper:#fff;--wash:#f7f5f0;--accent:#0f766e;
--crit:#b42318;--med:#b45309;--low:#52606d;--ok:#0f766e}
*{box-sizing:border-box}
body{margin:0;background:var(--wash);color:var(--ink);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
main{max-width:980px;margin:0 auto;padding:40px 24px 64px;background:var(--paper);border-top:6px solid var(--accent)}
h1,h2,h3{font-family:Charter,"Bitstream Charter","Iowan Old Style",Georgia,serif;line-height:1.25}
h1{font-size:30px;margin:0 0 6px}
h2{font-size:21px;margin:44px 0 12px;padding-bottom:6px;border-bottom:2px solid var(--accent)}
h3{font-size:16px;margin:0 0 6px}
.meta{color:var(--muted);margin:0}
.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin-top:28px;border:1px solid var(--line)}
.summary div{padding:16px 18px;border-right:1px solid var(--line)}
.summary div:last-child{border-right:0}
.figure{font-family:Charter,Georgia,serif;font-size:34px;font-weight:700;display:block}
.label{color:var(--muted);font-size:13px}
.legend{display:flex;flex-wrap:wrap;gap:18px;font-size:13px;color:var(--muted);margin:8px 0 0}
.legend span::before{content:"";display:inline-block;width:18px;height:3px;margin-right:6px;vertical-align:middle;background:var(--c)}
.finding{border-left:4px solid var(--crit);padding:12px 16px;margin:14px 0;background:var(--wash)}
.finding.medium{border-left-color:var(--med)}.finding.low{border-left-color:var(--low)}
.finding p{margin:4px 0}.finding ul{margin:6px 0 6px 18px;padding:0}
.sev{display:inline-block;font-size:12px;font-weight:700;padding:1px 8px;border-radius:3px;color:#fff;background:var(--crit);margin-right:6px}
.sev.medium{background:var(--med)}.sev.low{background:var(--low)}
.table-wrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{font-weight:600;color:var(--muted)}
.s-On-track,.s-Achieved{color:var(--ok);font-weight:600}
.s-Off-track{color:var(--crit);font-weight:600}
.s-Insufficient-data{color:var(--muted)}
.disclaimer{margin-top:40px;color:var(--muted);font-size:13px}
@media print{body{background:#fff}main{padding:0}}
"""


def to_html(result: TrackerResult) -> str:
    e = escape
    L, F = result.latest, result.first
    sig = result.signins
    sig_card = (f'<div><span class="figure">{_pct(sig["without_mfa_pct"])}</span>'
                f'<span class="label">Successful sign-ins without MFA</span></div>' if sig["provided"] else "")
    proj_rows = "".join(
        f'<tr><td>{e(p.measure)}</td><td>{p.current_pct:.0f}%</td><td>{p.target_pct:.0f}% by {e(p.target_date)}</td>'
        f'<td class="s-{p.status.replace(" ", "-")}">{e(p.status)}</td><td>{e(p.explanation)}</td></tr>'
        for p in result.projections)
    dept_rows = "".join(
        f"<tr><td>{e(d['department'])}</td><td>{d['accounts']}</td><td>{_pct(d['mfa_pct'])}</td>"
        f"<td>{_pct(d['phishing_resistant_pct'])}</td>"
        f"<td>{'n/a' if d['change_pts'] is None else format(d['change_pts'], '+.0f') + ' pts'}</td>"
        f"<td>{d['without_mfa']}</td></tr>" for d in result.departments)
    mix_rows = "".join(f"<tr><td>{e(m['tier'])}</td><td>{m['accounts']}</td><td>{_pct(m['pct'])}</td>"
                       f"<td>{e(m['methods'])}</td></tr>" for m in result.method_mix)
    cards = []
    for g in grouped_findings(result):
        f = g["finding"]
        sev = f.severity if f.severity in ("medium", "low") else ""
        items = "".join(f"<li>{e(d)}</li>" for d in g["details"])
        cards.append(f'<div class="finding {sev}"><h3><span class="sev {sev}">{e(f.severity.title())}</span>'
                     f'{e(f.rule_id)}: {e(f.title)}</h3><p><strong>Controls:</strong> {e(", ".join(f.controls))}</p>'
                     f'<ul>{items}</ul><p><strong>Remediation:</strong> {e(f.remediation)}</p></div>')
    if not cards:
        cards.append("<p>No findings.</p>")
    signin_section = ""
    if sig["provided"]:
        rows = "".join(f"<tr><td>{e(b['client_app'])}</td><td>{e(b['application'])}</td>"
                       f"<td>{'Legacy protocol' if b['legacy'] else 'Modern, single-factor'}</td>"
                       f"<td>{b['sign_ins']}</td><td>{e(', '.join(b['users']))}</td></tr>" for b in sig["bypass"])
        spray = (f"<p>{sig['failed_legacy_sign_ins']} failed sign-in attempts used legacy protocols. Repeated "
                 f"failures on legacy protocols are a common sign of password-spraying attacks.</p>"
                 if sig["failed_legacy_sign_ins"] else "")
        signin_section = (
            f"<h2>Where MFA is bypassed</h2><p>{sig['without_mfa']} of {sig['successful_sign_ins']} successful sign-ins "
            f"({_pct(sig['without_mfa_pct'])}) completed without MFA, including {sig['legacy_sign_ins']} through legacy "
            f"protocols that cannot perform MFA at all.</p>{spray}"
            + (f'<div class="table-wrap"><table><thead><tr><th>Client</th><th>Application</th><th>Type</th>'
               f'<th>Sign-ins</th><th>Users</th></tr></thead><tbody>{rows}</tbody></table></div>' if rows else ""))
    legend = (f'<div class="legend"><span style="--c:{COLORS["coverage"]}">MFA coverage</span>'
              f'<span style="--c:{COLORS["pr"]}">Phishing-resistant, all accounts</span>'
              f'<span style="--c:{COLORS["admin"]}">Phishing-resistant, administrators (dashed)</span>'
              f'<span style="--c:{COLORS["target"]}">Target</span></div>')
    target = result.projections[0].target_pct if result.projections else 100.0
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MFA rollout report: {e(result.organization)}</title>
<style>{_CSS}</style></head>
<body><main>
<h1>MFA rollout report: {e(result.organization)}</h1>
<p class="meta">{len(result.snapshots)} monthly snapshots, {e(_month(F.snapshot))} to {e(_month(L.snapshot))}. Generated {e(result.generated_at)} by mfa_tracker {e(result.tool_version)}.</p>
<section class="summary" aria-label="Summary">
<div><span class="figure">{_pct(L.mfa_pct)}</span><span class="label">MFA coverage (from {_pct(F.mfa_pct)})</span></div>
<div><span class="figure">{_pct(L.admin_phishing_resistant_pct)}</span><span class="label">Admins with phishing-resistant MFA</span></div>
<div><span class="figure">{_pct(L.phishing_resistant_pct)}</span><span class="label">Phishing-resistant, all accounts</span></div>
{sig_card}
</section>
<h2>Progress toward targets</h2>
<div class="table-wrap"><table><thead><tr><th>Measure</th><th>Now</th><th>Target</th><th>Status</th><th>Outlook</th></tr></thead><tbody>{proj_rows}</tbody></table></div>
<h2>Coverage over time</h2>
{trend_svg(result, target)}
{legend}
{signin_section}
<h2>Departments</h2>
<div class="table-wrap"><table><thead><tr><th>Department</th><th>Accounts</th><th>MFA</th><th>Phishing-resistant</th><th>Change since first snapshot</th><th>Without MFA</th></tr></thead><tbody>{dept_rows}</tbody></table></div>
<h2>Method strength</h2>
<div class="table-wrap"><table><thead><tr><th>Strength</th><th>Accounts</th><th>Share</th><th>Methods in use</th></tr></thead><tbody>{mix_rows}</tbody></table></div>
<h2>Findings by priority</h2>
{''.join(cards)}
<p class="disclaimer">{e(DISCLAIMER)}</p>
</main></body></html>
"""


WRITERS = {"json": to_json, "csv": to_csv, "md": to_markdown, "html": to_html}
